// Generated by view binder compiler. Do not edit!
package com.example.library_app_java.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.library_app_java.R;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBookBorrowingBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final EditText BookBorrowID;

  @NonNull
  public final TextView BookBorrowTitle;

  @NonNull
  public final MaterialButton bookBorrowBtn;

  @NonNull
  public final TextView borrowBackBtn;

  @NonNull
  public final EditText memBorrowID;

  @NonNull
  public final RadioButton radioBorrowBorrowed;

  @NonNull
  public final RadioButton radioBorrowNotAvailable;

  @NonNull
  public final RadioGroup radioGroupBorrowBookStatus;

  @NonNull
  public final RadioGroup radioGroupBorrowMemStatus;

  @NonNull
  public final TextView textViewBorrowBookStatus;

  @NonNull
  public final TextView textViewBorrowMemStatus;

  private ActivityBookBorrowingBinding(@NonNull RelativeLayout rootView,
      @NonNull EditText BookBorrowID, @NonNull TextView BookBorrowTitle,
      @NonNull MaterialButton bookBorrowBtn, @NonNull TextView borrowBackBtn,
      @NonNull EditText memBorrowID, @NonNull RadioButton radioBorrowBorrowed,
      @NonNull RadioButton radioBorrowNotAvailable, @NonNull RadioGroup radioGroupBorrowBookStatus,
      @NonNull RadioGroup radioGroupBorrowMemStatus, @NonNull TextView textViewBorrowBookStatus,
      @NonNull TextView textViewBorrowMemStatus) {
    this.rootView = rootView;
    this.BookBorrowID = BookBorrowID;
    this.BookBorrowTitle = BookBorrowTitle;
    this.bookBorrowBtn = bookBorrowBtn;
    this.borrowBackBtn = borrowBackBtn;
    this.memBorrowID = memBorrowID;
    this.radioBorrowBorrowed = radioBorrowBorrowed;
    this.radioBorrowNotAvailable = radioBorrowNotAvailable;
    this.radioGroupBorrowBookStatus = radioGroupBorrowBookStatus;
    this.radioGroupBorrowMemStatus = radioGroupBorrowMemStatus;
    this.textViewBorrowBookStatus = textViewBorrowBookStatus;
    this.textViewBorrowMemStatus = textViewBorrowMemStatus;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBookBorrowingBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBookBorrowingBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_book_borrowing, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBookBorrowingBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Book_borrow_ID;
      EditText BookBorrowID = ViewBindings.findChildViewById(rootView, id);
      if (BookBorrowID == null) {
        break missingId;
      }

      id = R.id.Book_borrow_Title;
      TextView BookBorrowTitle = ViewBindings.findChildViewById(rootView, id);
      if (BookBorrowTitle == null) {
        break missingId;
      }

      id = R.id.book_borrow_btn;
      MaterialButton bookBorrowBtn = ViewBindings.findChildViewById(rootView, id);
      if (bookBorrowBtn == null) {
        break missingId;
      }

      id = R.id.borrow_back_btn;
      TextView borrowBackBtn = ViewBindings.findChildViewById(rootView, id);
      if (borrowBackBtn == null) {
        break missingId;
      }

      id = R.id.mem_borrow_ID;
      EditText memBorrowID = ViewBindings.findChildViewById(rootView, id);
      if (memBorrowID == null) {
        break missingId;
      }

      id = R.id.radio_borrow_borrowed;
      RadioButton radioBorrowBorrowed = ViewBindings.findChildViewById(rootView, id);
      if (radioBorrowBorrowed == null) {
        break missingId;
      }

      id = R.id.radio_borrow_NotAvailable;
      RadioButton radioBorrowNotAvailable = ViewBindings.findChildViewById(rootView, id);
      if (radioBorrowNotAvailable == null) {
        break missingId;
      }

      id = R.id.radio_group_borrow_book_status;
      RadioGroup radioGroupBorrowBookStatus = ViewBindings.findChildViewById(rootView, id);
      if (radioGroupBorrowBookStatus == null) {
        break missingId;
      }

      id = R.id.radio_group_borrow_mem_status;
      RadioGroup radioGroupBorrowMemStatus = ViewBindings.findChildViewById(rootView, id);
      if (radioGroupBorrowMemStatus == null) {
        break missingId;
      }

      id = R.id.textView_borrow_Book_Status;
      TextView textViewBorrowBookStatus = ViewBindings.findChildViewById(rootView, id);
      if (textViewBorrowBookStatus == null) {
        break missingId;
      }

      id = R.id.textView_borrow_mem_Status;
      TextView textViewBorrowMemStatus = ViewBindings.findChildViewById(rootView, id);
      if (textViewBorrowMemStatus == null) {
        break missingId;
      }

      return new ActivityBookBorrowingBinding((RelativeLayout) rootView, BookBorrowID,
          BookBorrowTitle, bookBorrowBtn, borrowBackBtn, memBorrowID, radioBorrowBorrowed,
          radioBorrowNotAvailable, radioGroupBorrowBookStatus, radioGroupBorrowMemStatus,
          textViewBorrowBookStatus, textViewBorrowMemStatus);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
