// Generated by view binder compiler. Do not edit!
package com.example.library_app_java.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.library_app_java.R;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityReturnBookBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final EditText BookReturnID;

  @NonNull
  public final TextView BookReturnTitle;

  @NonNull
  public final MaterialButton bookReturnBtn;

  @NonNull
  public final EditText memReturnID;

  @NonNull
  public final RadioGroup radioGroupReturnBookStatus;

  @NonNull
  public final RadioGroup radioGroupReturnMemStatus;

  @NonNull
  public final RadioButton radioReturnAvailable;

  @NonNull
  public final RadioButton radioReturnNotborrowed;

  @NonNull
  public final TextView returnBackBtn;

  @NonNull
  public final TextView textViewReturnBookStatus;

  @NonNull
  public final TextView textViewReturnMemStatus;

  private ActivityReturnBookBinding(@NonNull RelativeLayout rootView,
      @NonNull EditText BookReturnID, @NonNull TextView BookReturnTitle,
      @NonNull MaterialButton bookReturnBtn, @NonNull EditText memReturnID,
      @NonNull RadioGroup radioGroupReturnBookStatus, @NonNull RadioGroup radioGroupReturnMemStatus,
      @NonNull RadioButton radioReturnAvailable, @NonNull RadioButton radioReturnNotborrowed,
      @NonNull TextView returnBackBtn, @NonNull TextView textViewReturnBookStatus,
      @NonNull TextView textViewReturnMemStatus) {
    this.rootView = rootView;
    this.BookReturnID = BookReturnID;
    this.BookReturnTitle = BookReturnTitle;
    this.bookReturnBtn = bookReturnBtn;
    this.memReturnID = memReturnID;
    this.radioGroupReturnBookStatus = radioGroupReturnBookStatus;
    this.radioGroupReturnMemStatus = radioGroupReturnMemStatus;
    this.radioReturnAvailable = radioReturnAvailable;
    this.radioReturnNotborrowed = radioReturnNotborrowed;
    this.returnBackBtn = returnBackBtn;
    this.textViewReturnBookStatus = textViewReturnBookStatus;
    this.textViewReturnMemStatus = textViewReturnMemStatus;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityReturnBookBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityReturnBookBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_return_book, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityReturnBookBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Book_return_ID;
      EditText BookReturnID = ViewBindings.findChildViewById(rootView, id);
      if (BookReturnID == null) {
        break missingId;
      }

      id = R.id.Book_return_Title;
      TextView BookReturnTitle = ViewBindings.findChildViewById(rootView, id);
      if (BookReturnTitle == null) {
        break missingId;
      }

      id = R.id.book_return_btn;
      MaterialButton bookReturnBtn = ViewBindings.findChildViewById(rootView, id);
      if (bookReturnBtn == null) {
        break missingId;
      }

      id = R.id.mem_return_ID;
      EditText memReturnID = ViewBindings.findChildViewById(rootView, id);
      if (memReturnID == null) {
        break missingId;
      }

      id = R.id.radio_group_return_book_status;
      RadioGroup radioGroupReturnBookStatus = ViewBindings.findChildViewById(rootView, id);
      if (radioGroupReturnBookStatus == null) {
        break missingId;
      }

      id = R.id.radio_group_return_mem_status;
      RadioGroup radioGroupReturnMemStatus = ViewBindings.findChildViewById(rootView, id);
      if (radioGroupReturnMemStatus == null) {
        break missingId;
      }

      id = R.id.radio_return_Available;
      RadioButton radioReturnAvailable = ViewBindings.findChildViewById(rootView, id);
      if (radioReturnAvailable == null) {
        break missingId;
      }

      id = R.id.radio_return_Notborrowed;
      RadioButton radioReturnNotborrowed = ViewBindings.findChildViewById(rootView, id);
      if (radioReturnNotborrowed == null) {
        break missingId;
      }

      id = R.id.return_back_btn;
      TextView returnBackBtn = ViewBindings.findChildViewById(rootView, id);
      if (returnBackBtn == null) {
        break missingId;
      }

      id = R.id.textView_return_Book_Status;
      TextView textViewReturnBookStatus = ViewBindings.findChildViewById(rootView, id);
      if (textViewReturnBookStatus == null) {
        break missingId;
      }

      id = R.id.textView_return_mem_Status;
      TextView textViewReturnMemStatus = ViewBindings.findChildViewById(rootView, id);
      if (textViewReturnMemStatus == null) {
        break missingId;
      }

      return new ActivityReturnBookBinding((RelativeLayout) rootView, BookReturnID, BookReturnTitle,
          bookReturnBtn, memReturnID, radioGroupReturnBookStatus, radioGroupReturnMemStatus,
          radioReturnAvailable, radioReturnNotborrowed, returnBackBtn, textViewReturnBookStatus,
          textViewReturnMemStatus);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
